import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { simpleGit } from "simple-git";
import { writeFile, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

async function assertAdmin(supabase: any, userId: string) {
  const { data, error } = await supabase
    .from("admins")
    .select("user_id")
    .eq("user_id", userId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Forbidden: not an admin");
}

async function loadApp(supabase: any, appId: string) {
  const { data, error } = await supabase
    .from("apps")
    .select("*")
    .eq("id", appId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("App not found");
  return data;
}

function getGithubPAT() {
  const token = process.env.GITHUB_PAT;
  if (!token) throw new Error("GITHUB_PAT not configured");
  return token;
}

export const uploadAndGenerateAsset = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) =>
    z
      .object({
        appId: z.string().uuid(),
        type: z.enum(["icon", "splash"]),
        imageData: z.instanceof(Uint8Array),
        imageDarkData: z.instanceof(Uint8Array).optional(),
        splashBgColor: z.string().optional(),
        splashBgColorDark: z.string().optional(),
      })
      .parse(input)
  )
  .handler(async ({ data, context }) => {
    // Verify admin permissions
    await assertAdmin(context.supabase, context.userId);

    // Load app data
    const app = await loadApp(context.supabase, data.appId);

    // Validate image data
    if (data.imageData.length > 5 * 1024 * 1024) {
      throw new Error("Image size must be less than 5MB");
    }
    if (data.imageDarkData && data.imageDarkData.length > 5 * 1024 * 1024) {
      throw new Error("Dark mode image size must be less than 5MB");
    }

    const token = getGithubPAT();
    const timestamp = Date.now();
    const tempDir = join(tmpdir(), `bgp-assets-${data.appId}-${timestamp}`);

    try {
      // Clone the repository
      const repoUrl = `https://x-access-token:${token}@github.com/${app.github_owner}/${app.github_repo}.git`;
      const git = simpleGit();

      console.log(`Cloning ${app.github_owner}/${app.github_repo} to ${tempDir}...`);
      await git.clone(repoUrl, tempDir, ["--depth", "1", "--branch", app.default_ref]);

      // Initialize git in the cloned directory
      const repoGit = simpleGit(tempDir);
      await repoGit.addConfig("user.name", "BGP Admin Bot");
      await repoGit.addConfig("user.email", "admin@biblegames.dev");

      // Create assets directory if it doesn't exist
      const assetsDir = join(tempDir, "assets");
      await mkdir(assetsDir, { recursive: true });

      // Save uploaded images
      const lightFileName = data.type === "icon" ? "logo.png" : "splash.png";
      const darkFileName = data.type === "icon" ? "logo-dark.png" : "splash-dark.png";

      await writeFile(join(assetsDir, lightFileName), data.imageData);
      console.log(`Saved ${lightFileName} to assets/`);

      if (data.imageDarkData) {
        await writeFile(join(assetsDir, darkFileName), data.imageDarkData);
        console.log(`Saved ${darkFileName} to assets/`);
      }

      // Run @capacitor/assets to generate all sizes
      console.log("Running @capacitor/assets to generate all required sizes...");

      // Import capacitor assets dynamically
      const { loadContext } = await import("@capacitor/assets/dist/ctx");
      const { run } = await import("@capacitor/assets/dist/tasks/generate");

      const ctx = await loadContext(tempDir);
      ctx.args = {
        iconBackgroundColor: "#ffffff",
        splashBackgroundColor: data.splashBgColor || "#ffffff",
        splashBackgroundColorDark: data.splashBgColorDark || "#000000",
        silent: false,
      };

      await run(ctx);
      console.log("Asset generation complete!");

      // Stage all changes
      await repoGit.add(".");

      // Check if there are changes to commit
      const status = await repoGit.status();
      if (status.files.length === 0) {
        throw new Error("No changes to commit - assets may already be up to date");
      }

      // Commit changes
      const assetType = data.type === "icon" ? "app icon" : "splash screen";
      const commitMessage = `chore: update ${assetType} via bgp-admin\n\nGenerated by BGP Admin Panel\nAsset type: ${data.type}\nDark mode: ${data.imageDarkData ? "yes" : "no"}`;

      await repoGit.commit(commitMessage);
      console.log("Changes committed");

      // Push to remote
      await repoGit.push("origin", app.default_ref);
      console.log("Changes pushed to GitHub");

      // Get the commit SHA for the URL
      const log = await repoGit.log(["-1"]);
      const commitSha = log.latest?.hash;

      // Cache icon as base64 data URL on apps row for fast list rendering.
      // Only for icons, and only when payload is small enough (<= 500KB raw).
      if (data.type === "icon" && data.imageData.length <= 500 * 1024) {
        const base64 = Buffer.from(data.imageData).toString("base64");
        const dataUrl = `data:image/png;base64,${base64}`;
        const { error: updErr } = await context.supabase
          .from("apps")
          .update({ icon_data_url: dataUrl })
          .eq("id", data.appId);
        if (updErr) {
          console.error("Failed to cache icon_data_url:", updErr.message);
        }
      }

      return {
        success: true,
        commitUrl: commitSha
          ? `https://github.com/${app.github_owner}/${app.github_repo}/commit/${commitSha}`
          : undefined,
        message: `${assetType.charAt(0).toUpperCase() + assetType.slice(1)} generated and committed successfully`,
      };
    } catch (error) {
      console.error("Asset generation failed:", error);
      throw error instanceof Error ? error : new Error("Asset generation failed");
    } finally {
      // Clean up temporary directory
      try {
        await rm(tempDir, { recursive: true, force: true });
        console.log(`Cleaned up temp directory: ${tempDir}`);
      } catch (cleanupError) {
        console.error("Failed to cleanup temp directory:", cleanupError);
        // Don't throw - the main operation completed
      }
    }
  });
